<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <None Include="app.ico" CopyToOutputDirectory="PreserveNewest" />
    <RootNamespace>PCITLauncher</RootNamespace>
    <AssemblyName>PCITLauncher</AssemblyName>
  </PropertyGroup>

</Project>
